import Head from 'next/head';

const Privacy = () => {
    return (
        <div
            style={{
                color: 'black',
                background: 'white'
            }}
        >
            <Head>
                <title>Sách nói & Podcast Chất lượng cao. 100% Bản quyền | Voiz FM</title>
                <meta property="fb:app_id" content={process.env.NEXT_PUBLIC_FACEBOOK_APP_ID} />
                <meta property="og:url" content="https://voiz.vn" />
                <meta property="og:type" content="website" />
                <meta property="og:title" content="Sách nói & Podcast Chất lượng cao. 100% Bản quyền | Voiz FM" />
                <meta
                    property="og:description"
                    content="Sách nói bán chạy. Đọc truyện đêm khuya. Tin tức hàng ngày. Podcast hữu ích. Cập nhật thường xuyên."
                />
                <meta property="og:image" content="https://voiz.vn/images/logo_voiz.jpg" />
                <meta property="og:image:width" content="1200" />
                <meta property="og:image:height" content="630" />
            </Head>
            <div
                style={{
                    width: '80%',
                    margin: '0 auto',
                    paddingTop: '40px'
                }}
            >
                <h3 dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'center', marginTop: '0pt', marginBottom: '4pt' }}><span style={{ fontSize: '18pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>PRIVACY POLICY</span></h3>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'italic', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>Last updated: June 01, 2022</span></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>This Privacy Policy explains who we are, how we process (i.e. collect, record, organize, structure, store, adapt or alter, retrieve, consult, use, disclose by transmission, disseminate or otherwise make available, align or combinate, restrict, erase or destruct) personal information about you, and how you can exercise your privacy rights.&nbsp;</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333',  fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>We are</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333',  fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;WeWe Technology JSC</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333',  fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>, a company under laws of Vietnam, with registered address at:&nbsp;</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333',  fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>44 Le Van Duyet Street, Binh Thanh District, HCMCT, the owner of Voiz FM - the high-quality audio platform, 100% copyright</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;that are made available via app stores including the Apple App Store and Google Play Store. This Privacy Policy applies to personal information that we&nbsp;</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333',  fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>collect through our website, mobile applications.&nbsp;</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>By using our Services, you agree to be bound by this Privacy Policy and consent to our processing of information as specified therein.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>1. INFORMATION WE COLLECT FROM YOU</span></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>Most of the information that we&nbsp;</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333',  fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>collect about you comes directly from you when you use our website or mobile app.</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;In general, the information we collect about you relates to the type of device you are using, information that&nbsp;</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333',  fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>helps us identify your device, how you use our mobile app</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;and may include information that you submit to us when you voluntarily contact us. We may also collect information from app store platforms and partners and other third parties such as information about your interests and in-app purchases (provided that we never receive your payment or credit card information).</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>The information that we may collect about you through the Services broadly falls into the following categories:</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>(a) Information that you provide voluntarily</span></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>Certain parts of our Services may ask you to provide personal information voluntarily. For example, we will ask for certain information in order for you to submit enquiries to us, such as:</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333',  fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>- your name, email address, phone number, image or other details, necessary to process your inquiries;</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>- any information you submit to our support team via email.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>The personal information that you are asked to provide and the reasons why you are asked to provide it, we will try to explain to you at the point we ask you to provide your personal information.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>(b) Information that we collect automatically</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>When you use our Services, we may also collect certain information automatically from you and/or your device which may be considered personal information under applicable data protection laws, such as:</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333',  fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>- Data and analytics about your use of our Services (e.g. in-app search log, in-app interaction, installed apps, etc)</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>- Your device type and the operating system that you use</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>- Broad geographic location (e.g. country or city-level location) based on your IP address</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>Some of this information may be collected through cookies as explained further under the heading&nbsp;</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>Cookies</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;below.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>(c) Information we obtain from third-party sources</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>- Third-Party Social Network/s</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>. Google Play Games Service, Apple Game Center, Facebook (“Third-Party Social Network/s”). You may choose to connect to our Services via your social media account. Exactly what information we receive from your social media will depend on your social media privacy settings, but it would typically include your basic public profile information such as your username, gender, your friends. (See below also “Third-Party Social Networks”).</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>- Third party service providers</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>. We may receive personal information about you from third-party sources.&nbsp;</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333',  fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>We may get your personal information for example when you installed our app and prior to installing you have clicked an advertisement for the same service.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>- Advertising partners</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>. From time to time, we may also receive personal information about you from other third-party sources. For example, if you clicked on an advertisement to direct you to one of our Services (such as an advert of one of our audiobooks in another publisher’s game), we will be provided with information from which ad network and advertising campaign the install originated from (See below also “Advertising”).</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>A list of our current service providers and partners is available&nbsp;</span><a href="https://indiez.net/third-party-service-providers.html" style={{ textDecoration: 'none' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>here</span></a><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>(d) No special categories of information</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>We do not request or intend to collect any “special categories of information” such as personal data revealing racial or ethnic origin, political opinions, religious or philosophical beliefs, or trade union membership, genetic data, biometric data for the purpose of uniquely identifying a natural person, data concerning health or data concerning a natural person’s sex life or sexual orientation. Kindly be cautious when sharing this information about yourself (or others) in our forums.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>2. HOW WE USE YOUR INFORMATION</span></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>2.1. In General</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>We use the information we collect about you/your device to deliver services and our audiobooks to you and to operate our business. We use it also for improving our services and audiobooks, for enhancing security and for analytics and research purposes to make sure we provide you with the best experience. In addition, we use your information to promote our services and audiobooks in our app and also in other publisher’s apps and to display third-party advertisements to you. We use your information also for tracking and fraud prevention for advertising purposes and for complying with our legal obligations.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>We use your information for the following&nbsp;</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>purposes</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>:</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>1. Delivering and improving our services.</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;We use your information for developing, delivering and improving our app and other products, services, and content, tailoring our products and services, providing audiobook updates, technical troubleshooting, understanding and analyzing trends in connection with usage of the audiobooks, and administering the audiobooks.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>2. Displaying advertisements.</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;We use your information for showing advertisements for our audiobooks in other publisher’s apps and for displaying third-party advertisements in our app. Please see more in the Advertising Section of this Privacy Policy.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>3. Cross-promotion.</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;We use your information for cross-promoting our audiobooks and services, meaning to promote one of our audiobooks while you are listening to a different audiobook of ours. &nbsp;</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>4. Tracking and fraud prevention for advertising purposes.</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;We use your information for tracking how our advertising campaigns perform and for identifying and preventing fraud for our advertising campaigns.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>5. Analytics and research.</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;We use your information for understanding and analyzing trends in connection with the usage of the app, gathering demographic information about our user base, and data about where the app was downloaded from. We may also create reports and analysis for the purposes of research or business intelligence, for example to track potential problems or trends with our app and services, or to test our new audiobook features and content.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>6. Security.</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;We use your information for enhancing the safety and security of our app, products and services.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>7. Customer Support.</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;We use your information for providing customer support to you and to respond to your inquiries.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>8. Our legal obligations.</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;We use your information when we are required to do so by law, for example, we use your country or region for tax reporting purposes.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>2.2. In-App Purchases</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>Our audiobooks enable in-app purchases. We do not process payments for in-app purchases nor have access to your credit card information.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>Payment transactions for in-app purchases are completed through the app store via your App Store account, Google Play account. Any post-purchase processes are controlled by the Apple, Google stores and are subject to specific terms of such Apple, Google stores. Please review the privacy policy and terms of service of your Apple, Google stores.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>3. HOW WE SHARE YOUR INFORMATION</span></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>We cannot provide all services necessary for the successful operation of the app by ourselves. We must, therefore, share collected information with third parties for the purposes of developing and delivering our services, displaying advertisements, conducting analysis and research and for measuring our and our Partners’ advertising campaign performance. We also reserve the right to disclose your information (including personally identifiable information) when we are legally required to do so, to disclose your information in an anonymous and aggregated manner, meaning you could not be personally identified from it.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>We may share such information to:</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>- Our analytics providers.</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;We use third-party analytics for the purposes of delivering our services, conducting analysis, and research. The device data we share with such providers are encoded. The providers may assign a random ID to these data and they are not able to match it back to You. We can aggregate the data for benchmarking features.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>- Our cloud service providers.</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;We store information we collect from you on servers provided by our third-party cloud service providers such as iCloud, Google Cloud Platform;</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>- Our tracking and fraud prevention providers.</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;For some of our audiobooks we use tracking and fraud prevention providers for the purposes of measuring performance and optimizing our advertising campaigns, displaying advertisements, conducting analysis to improve our services and for fraud prevention purposes. Such providers may use APIs, and SDKs in our app to enable them to collect and analyze user and device-related data and information, such as impressions, clicks, installs or other advertising campaign performance indicators and post-install in-app events.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>- Third-party advertising partners.</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;We have contracted with certain third-party advertising networks that assist us in delivering advertising to you that allows us to continue offering the audiobooks for free or at low cost.&nbsp;</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>- Advertising partner’s third-party tracking provider.</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;We allow our advertising partners to track impressions, clicks, installs or other advertising campaign performance indicators through their tracking providers for the purposes of measuring their advertising campaign performance. They may use their own third-party tracking providers.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>We may contract with additional Partners or change existing Partners in the future to perform any services in connection with the app. These changes shall be updated from time to time or promptly in case of material changes in our data processing practices.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>The list of our current service providers and partners is available&nbsp;</span><a href="https://indiez.net/third-party-service-providers.html" style={{ textDecoration: 'none' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>here</span></a><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>We reserve the right to disclose your information (including personally identifiable information) in response to law, legal process, litigation, and/or requests from public and governmental authorities within or outside your country of residence. We may also disclose information about you if we determine that for purposes of national security, law enforcement, or other issues of public importance, the disclosure is necessary or appropriate. We may also disclose information about you if we determine that disclosure is reasonably necessary to enforce our terms and conditions or to protect our operations, users or user experience. Additionally, in the event of a reorganization, merger or sale we may transfer any and all information (including personally identifiable information) we collect to the relevant third party.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>4. THIRD-PARTY SOCIAL NETWORKS</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>5.1. Connecting to Third-Party Social Networks</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>Our app uses third-party services such as Google Play Games Service, Apple Game Center, Facebook (“Third Party Social Network/s”). The app enables you to log in to your Third-Party Social Network account to connect our App by using the “Log in” feature in our App. You may also share the content you create within the App on Third-Party Social Networks. Please note, Third Party Social Networks are governed by their own privacy policies, terms and end-user agreements and we are not responsible for and have no control over the sharing practices or policies of the third parties that operate those sites.&nbsp;</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>5.2. Information We May Receive When You Connect to Third-Party Social Networks</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>The information you allow us to access varies by App and is affected by the privacy settings you establish on those Third-Party Social Networks. You can control and find out more about these settings from the Third-Party Social Network in question. When you use the “Log in” feature, we may access and store some or all of the following information, as allowed by you, Third-Party Social Networks and your preferences: (i) your basic information from your public profile, such as your nickname, profile picture; (ii) login ID and/or player identifier string; (iii) list of your friends; (iv) any other information which is detailed and displayed to you in the notice which appears during the “Log in with” process.&nbsp;</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>The App may further ask you to allow us to post on such Third-Party Social Networks on your behalf (e.g. status updates). Please keep in mind that we will only do that if specifically allowed by you and we will store ID and your full name for the purposes of user identification. Other information will be merely stored within the App on your device so that the App will be able to communicate with Third Party Social Network directly.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>5. COOKIES</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>Cookies are files with a small amount of data, which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your computer’s hard drive.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>We use “cookies” to collect information. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some options of our Service.</span></p>
                <p><br /></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>6. YOUR RIGHTS</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333',  fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>You have certain rights in connection with your personal information and how we handle it. Some of these rights may be subject to some exceptions or limitations. You can exercise these rights at any time by following the instructions below or sending us relevant requests to&nbsp;</span><a href="mailto:marketing@wewe.vn" style={{ textDecoration: 'none' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#1155cc',  fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'underline', WebkitTextDecorationSkip: 'none', textDecorationSkipInk: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>marketing@wewe.vn</span></a><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#5f6368',  fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>.&nbsp;</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>Your rights include:</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>- Right to correct your data</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;(e.g. you can contact us if your email address has been changed and we should replace your old email address)</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>-</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333',  fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;Right to have your data deleted</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333',  fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;(e.g. you can contact us if you want us to delete certain data that we have stored about you)</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>- Right to restrict processing</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;of your personal information (e.g. you can contact us if you want to restrict processing)</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>- Right to take your data with you</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;(e.g. you can contact us to receive your data if you want to upload it to another service)</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>- Right to object how your data is handled</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;(e.g. you can contact us if you do not agree with any user analytics procedures as described within this privacy policy)</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>- Right to send complaints</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>&nbsp;to the supervisory authority (e.g. you can contact the data protection supervisory authority directly).</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>7. GENERAL</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>Your information privacy and security is important to us and we always pay special attention to ensure that we process your information lawfully. We store your information for as long as needed to provide you with our services. We may store information longer, but only in a way that it cannot be tracked back to you. Please check regularly for changes to our Privacy Policy.</span></p>
                <p><br /></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>8. SECURITY</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>We have implemented appropriate technical and organizational measures to protect the confidentiality, security and integrity of the collected information, and to prevent unauthorized access and the use of information contrary to this Privacy Policy. Although we use commercially reasonable efforts to assure that your information remains secure when maintained by us, please be aware that no security measures are perfect or impenetrable.</span></p>
                <p><br /></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>9. RETENTION</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>We store your information for as long as needed to provide you with our services. We may store information longer, but only in a way that it cannot be tracked back to you. We delete the information as soon as we do not need it for the purposes as described in this Privacy Policy and in any event no later than five (5) years after your interaction with all of our audiobooks has ceased.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>When required by law, we will retain your information for as long as we are legally obligated to do so. If you request us to delete your data we will delete your data as described above in “Your Rights” Section.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>10. CHANGES TO OUR PRIVACY POLICY</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>We will occasionally update this Privacy Policy as necessary to protect our users, furnish current information, and respond to legal and technical changes. For previous versions of this Privacy Policy, please contact us via&nbsp;</span><a href="mailto:marketing@wewe.vn" style={{ textDecoration: 'none' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#1155cc', backgroundColor: '#ffffff', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'underline', WebkitTextDecorationSkip: 'none', textDecorationSkipInk: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>marketing@wewe.vn</span></a><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#5f6368', backgroundColor: '#ffffff', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>.&nbsp;</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>11. CONTACT US</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>If you have questions or concerns about this Privacy Policy, please contact us through one of the following ways:</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>1. for privacy questions and exercising your rights via our privacy email:&nbsp;</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#5f6368', backgroundColor: '#ffffff', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>marketing@wewe.vn</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>;</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>2. If you have a concern or compliance regarding our treatment of your personal data you can contact the relevant data protection authority. For more information on which authority to contact, please email us here&nbsp;</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#5f6368', backgroundColor: '#ffffff', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>marketing@wewe.vn</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>.</span></p>
                <p><br /></p>
                <p dir="ltr" style={{ lineHeight: '1.7999999999999998', textAlign: 'justify', marginTop: '0pt', marginBottom: '12pt' }}><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333', backgroundColor: 'transparent', fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>For information collected under this Privacy Policy, the data controller is&nbsp;</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333',  fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>WeWe Technology JSC</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333',  fontWeight: 400, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>, a company under laws of Vietnam, with registered address at:&nbsp;</span><span style={{ fontSize: '13pt', fontFamily: '"Times New Roman"', color: '#333333',  fontWeight: 700, fontStyle: 'normal', fontVariant: 'normal', textDecoration: 'none', verticalAlign: 'baseline', whiteSpace: 'pre-wrap' }}>44 Le Van Duyet Street, Binh Thanh District, HCMCT, the owner of Voiz FM - the high-quality audio platform, 100% copyright</span></p>
                <p><br /></p>
            </div >
        </div >
    )
}

export default Privacy