export const messages = {
    'momo': {
        '0': 'Giao dịch thành công',
        '9000': 'Giao dịch đã được xác nhận thành công',
        '8000': 'Giao dịch đang ở trạng thái cần được người dùng xác nhận thanh toán lại',
        '7000': 'Giao dịch đang được xử lý',
        '1000': 'Giao dịch đã được khởi tạo, chờ người dùng xác nhận thanh toán',
        '11': 'Truy cập bị từ chối',
        '12': 'Phiên bản API không được hỗ trợ cho yêu cầu này',
        '13': 'Xác thực doanh nghiệp thất bại',
        '20': 'Yêu cầu sai định dạng',
        '21': 'Số tiền giao dịch không hợp lệ',
        '40': 'RequestId bị trùng',
        '41': 'OrderId bị trùng',
        '42': 'OrderId không hợp lệ hoặc không được tìm thấy',
        '43': 'Yêu cầu bị từ chối vì xung đột trong quá trình xử lý giao dịch',
        '1001': 'Giao dịch thanh toán thất bại do tài khoản người dùng không đủ tiền.Yes',
        '1002': 'Giao dịch bị từ chối do nhà phát hành tài khoản thanh toán',
        '1003': 'Giao dịch bị đã bị hủy',
        '1004': 'Giao dịch thất bại do số tiền thanh toán vượt quá hạn mức thanh toán của người dùng',
        '1005': 'Giao dịch thất bại do url hoặc QR code đã hết hạn',
        '1006': 'Giao dịch thất bại do người dùng đã từ chối xác nhận thanh toán',
        '1007': 'Giao dịch bị từ chối vì tài khoản người dùng đang ở trạng thái tạm khóa',
        '1026': 'Giao dịch bị hạn chế theo thể lệ chương trình khuyến mãi',
        '1080': 'Giao dịch hoàn tiền bị từ chối. Giao dịch thanh toán ban đầu không được tìm thấy',
        '1081': 'Giao dịch hoàn tiền bị từ chối. Giao dịch thanh toán ban đầu có thể đã được hoàn',
        '2001': 'Giao dịch thất bại do sai thông tin liên kết',
        '2007': 'Giao dịch thất bại do liên kết hiện đang bị tạm khóa',
        '3001': 'Liên kết thất bại do người dùng từ chối xác nhận.Yes',
        '3002': 'Liên kết bị từ chối do không thỏa quy tắc liên kết',
        '3003': 'Hủy liên kết bị từ chối do đã vượt quá số lần hủy',
        '3004': 'Liên kết này không thể hủy do có giao dịch đang chờ xử lý',
        '4001': 'Giao dịch bị hạn chế do người dùng chưa hoàn tất xác thực tài khoản.Yes',
        '4010': 'Quá trình xác minh OTP thất bại',
        '4011': 'OTP chưa được gửi hoặc hết hạn',
        '4100': 'Giao dịch thất bại do người dùng không đăng nhập thành công.Yes',
        '4015': 'Quá trình xác minh 3DS thất bại',
        '10': 'Hệ thống đang được bảo trì',
        '99': 'Lỗi không xác định'
    },
    'appota': {
        '0': 'Thành công',
        '1': 'Các tham số yêu cầu thiếu hoặc không hợp lệ',
        '2': 'Tham số signature không chính xác',
        '11': 'Partner không tồn tại',
        '13': 'Partner đã bị khoá',
        '14': 'API KEY không đúng',
        '15': 'Sẩn phẩm chưa được kích hoạt hoặc đã bị khoá',
        '21': 'Sai otp',
        '30': 'Mã đơn hàng bị trùng',
        '32': 'Số tiền thanh toán không hợp lệ',
        '33': 'Giao dịch không thành công do khách hàng không thực hiện giao dịch',
        '34': 'Giao dịch đang được xử lý, vui lòng thử lại sau',
        '35': 'Giao dịch đang chờ được xử lý, vui lòng thử lại sau',
        '36': 'Giao dịch không tồn tại',
        '37': 'Giao dịch không xác định',
        '38': 'Người dùng huỷ giao dịch',
        '40': 'Giao dịch đã được hoàn trả',
        '51': 'Mã ngân hàng không tồn tại',
        '52': 'Phương thức thanh toán không hợp lệ',
        '61': 'Giao dịch bị từ chối',
        '62': 'Ngân hàng đang bảo trì',
        '63': 'Thẻ chưa kích hoạt hoặc chưa đăng ký thanh toán online',
        '64': 'Loại thẻ chưa được hỗ trợ',
        '65': 'Thông tin thẻ không đúng',
        '66': 'Thẻ của bạn đang bị hạn chế, vui lòng liên hệ ngân hàng để biết thông tin chi tiết',
        '67': 'Thông tin ngày mở thẻ không đúng',
        '68': 'Thẻ của bạn đã bị khoá',
        '69': 'Thẻ của bạn đã hết hạn',
        '70': 'Bạn đã giao dịch vượt quá giới hạn cho phép trong ngày, vui lòng thử lại sau',
        '71': 'Thông tin tên chủ thẻ không đúng',
        '72': 'Cổng thanh toán không nhận được kết quả trả về từ ngân hàng phát hành thẻ',
        '73': 'Thông tin ngày hết hạn thẻ không đúng',
        '74': 'Thẻ không đủ hạn mức hoặc tài khoản không đủ số dư để thanh toán',
        '75': 'Số tiền không đủ để thanh toán',
        '76': 'Số thẻ không đúng',
        '77': 'Quá thời gian thanh toán',
        '78': 'Lỗi từ hệ thống ngân hàng, vui lòng thực hiện lại giao dịch',
        '79': 'Không thể xử lý thẻ của bạn, vui lòng liên hệ nhà cung câp để được hỗ trợ',
        '80': 'Mã CVC/CVV không chính xác',
        '81': 'Thẻ không hỗ trợ 3DS',
        '82': 'Thẻ của bạn đã bị từ chối giao dịch, vui lòng liên hệ để biết thông tin chi tiết',
        '83': 'Giao dịch bị từ chối, vui lòng liên hệ để biết thông tin chi tiết',
        '84': 'Số tiền giao dịch quá giới hạn cho phép, vui lòng liên hệ để được hỗ trợ',
        '85': 'Số lượng thẻ giao dịch quá giới hạn cho phép, vui lòng liên hệ để được hỗ trợ',
        '91': 'Hệ thống đang bận, vui lòng thử lại sau',
        '89': 'Thẻ của bạn bị từ chối (do quốc gia phát hành thẻ ko hợp lệ)',
        '92': 'IP không được phép truy cập',
        '94': 'Hệ thống đang bảo trì',
        '99': 'Lỗi không xác định, vui lòng kiểm tra lại giao dịch sau',
        '105': 'Số tiền hoàn lại không được quá số tiền giao dịch',
        '106': 'Giao dịch không hỗ trợ refund một phần',
        '110': 'Tổng số tiền refund vượt quá số tiền giao dịch',
        '120': 'Tài khoản của người dùng bị đóng băng',
        '121': 'Tài khoản ví của người dùng đã vượt quá giới hạn',
        '125': 'Không thể hoàn tiền cho giao dịch vì đã quá thời hạn hoàn tiền',
        '126': 'Giao dịch hoàn tiền không thành công do vi phạm quy định nhà cung cấp dịch vụ',
        '127': 'Yêu cầu hoàn lại tiền cho giao dịch thanh toán không thành công',
        '401': 'Lỗi xác thực ( do JWT Token không đúng hoặc đã hết hạn)',
        '500': 'Lỗi hệ thống'
    },
    'vnpay': {
        '00': 'Giao dịch thành công',
        '07': 'Trừ tiền thành công. Giao dịch bị nghi ngờ (liên quan tới lừa đảo, giao dịch bất thường)',
        '09': 'Thẻ/Tài khoản của khách hàng chưa đăng ký dịch vụ InternetBanking tại ngân hàng',
        '10': 'Khách hàng xác thực thông tin thẻ/tài khoản không đúng quá 3 lần',
        '11': 'Đã hết hạn chờ thanh toán. Xin quý khách vui lòng thực hiện lại giao dịch',
        '12': 'Thẻ/Tài khoản của khách hàng bị khóa',
        '13': 'Quý khách nhập sai mật khẩu xác thực giao dịch (OTP). Xin quý khách vui lòng thực hiện lại giao dịch',
        '24': 'Khách hàng hủy giao dịch',
        '51': 'Tài khoản của quý khách không đủ số dư để thực hiện giao dịch',
        '65': 'Tài khoản của Quý khách đã vượt quá hạn mức giao dịch trong ngày',
        '75': 'Ngân hàng thanh toán đang bảo trì',
        '79': 'KH nhập sai mật khẩu thanh toán quá số lần quy định. Xin quý khách vui lòng thực hiện lại giao dịch',
        '99': 'Giao dịch lỗi'
    }
}